#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev CA2-eth0 up
        ip link add link CA2-eth0 name CA2-eth0.303 type vlan id 0x303
        ip link set dev CA2-eth0.303 up
        
        sleep 20; dhclient -6 -pf /var/run/dhclient_CA2.pid -S CA2-eth0.303
        