#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev HA1-eth0 up
        ip link add link HA1-eth0 name HA1-eth0.200 type vlan id 0x200
        ip link set dev HA1-eth0.200 up
        
        sleep 20; rdnssd -H /etc/rdnssd/merge-hook -u rdnssd -p /var/run/HA1_rdnssd.pid
        