#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev HA2-eth0 up
        ip link add link HA2-eth0 name HA2-eth0.300 type vlan id 0x300
        ip link set dev HA2-eth0.300 up
        
        sleep 20; dhclient -6 -pf /var/run/dhclient_HA2.pid -S HA2-eth0.300
        