#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev HA3-eth0 up
        ip link add link HA3-eth0 name HA3-eth0.500 type vlan id 0x500
        ip link set dev HA3-eth0.500 up
        
        sleep 20; dhclient -6 -pf /var/run/dhclient_HA3.pid -S HA3-eth0.500
        