#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev HA4-eth0 up
        ip link add link HA4-eth0 name HA4-eth0.600 type vlan id 0x600
        ip link set dev HA4-eth0.600 up
        
        sleep 20; dhclient -6 -pf /var/run/dhclient_HA4.pid -S HA4-eth0.600
        