#!/bin/bash 

# This file has been generated automatically, see service_config_creation.py for details. 

ip link set dev NS2-eth0 up 
ip address add dev NS2-eth0 fd00:200:3:101::53/64 
ip address add dev NS2-eth0 fd00:300:3:101::53/64 

ip -6 route add ::/0 via fd00:200:3:101:: 

named -6 -c /etc/bind/named2.conf 

iperf3 -s -D

/usr/sbin/sshd

