#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev PY1-eth0 up
        ip link add link PY1-eth0 name PY1-eth0.201 type vlan id 0x201
        ip link set dev PY1-eth0.201 up
        
        sleep 20; rdnssd -H /etc/rdnssd/merge-hook -u rdnssd -p /var/run/PY1_rdnssd.pid
        