#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev PY2-eth0 up
        ip link add link PY2-eth0 name PY2-eth0.301 type vlan id 0x301
        ip link set dev PY2-eth0.301 up
        
        sleep 20; rdnssd -H /etc/rdnssd/merge-hook -u rdnssd -p /var/run/PY2_rdnssd.pid
        