#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev SH2-eth0 up
        ip link add link SH2-eth0 name SH2-eth0.305 type vlan id 0x305
        ip link set dev SH2-eth0.305 up
        
        sleep 20; dhclient -6 -pf /var/run/dhclient_SH2.pid -S SH2-eth0.305
        iperf3 -s -D

