#!/bin/bash 

# This file has been generated automatically, see host_config_creation.py for details. 


        ip link set dev ST1-eth0 up
        ip link add link ST1-eth0 name ST1-eth0.202 type vlan id 0x202
        ip link set dev ST1-eth0.202 up
        
        sleep 20; rdnssd -H /etc/rdnssd/merge-hook -u rdnssd -p /var/run/ST1_rdnssd.pid
        