#!/bin/bash


# You can override any of these settings on a per-topology basis
# Group number
GROUPNUMBER=255
# Node configs  
CONFIGDIR=example_cfg
PREFIXA="fd00:200:${GROUPNUMBER}::/48"
PREFIXB="fd00:300:${GROUPNUMBER}::/48"

# This function describes the network topology that we want to emulate
function mk_topo {
    echo "@@ Adding links and nodes"
    add_link MICH SH1C # mich-eth0 sh1c-eth0
    add_link SH1C HALL  # sh1c-eth1 hall-eth0 
    add_link HALL PYTH  # hall-eth1 pyth-eth0
    add_link STEV PYTH  # stev-eth0 pyth-eth1
    add_link STEV CARN  # stev-eth1 carn-eth0
    add_link CARN MICH  # carn-eth1 mich-eth1
    add_link PYTH CARN  # pyth-eth2 carn-eth2

    echo "@@ Adding LANs"
    mk_LAN MICH MI1 MI2
    mk_LAN SH1C SH1 SH2
    mk_LAN HALL HA1 HA2
    mk_LAN PYTH PY1 PY2
    mk_LAN STEV ST1 ST2
    mk_LAN CARN CA1 CA2


    echo "@@ Briding the network"
    bridge_node HALL eth1 belneta
    bridge_node PYTH eth2 belnetb
    # We likely want to have redundant connections to our 2 providers
    # bridge_node HALL eth1 HALL-belnetb
    # bridge_node PYTH eth2 HALL-belneta
    # We can add a test host 'outside of the network':
    # mk_node test300
    # bridge_node HALL eth1 test300
    # mk_node test200
    # bridge_node PYTH eth2 test200
    # These hosts will sit next to belneta and thus could be used to simulate
    # external inbound traffic sources. Make sure to set routes on
    # them, i.e. in test300_start, 
    # (i) Assign an address: ip address add dev test300 fd00:300::${GROUPNUMBER}:255/64
    # (ii) Add a default route: ip route add ::/0 via fd00:300::b
    # (iii) Add a route towards your network:
    # ip route add fd00:300:${GROUPNUMBER}::/48 via fd00:300::${GROUPNUMBER}

    echo "@@ Making the virtual network reachable from the host machine"
    # Enable IPv6 forwarding on the bridges
    sysctl -w net.ipv6.conf.breth1.forwarding=1
    sysctl -w net.ipv6.conf.breth2.forwarding=1
    # Add (hopefully) unique source addresses on the bridge
    ip address add dev breth1 "fd00:300::${GROUPNUMBER}:1/64"
    ip address add dev breth2 "fd00:200::${GROUPNUMBER}:1/64"
    # Route the vitual network prefixes over the bridges
    ip route add "$PREFIXB" via "fd00:300::${GROUPNUMBER}"
    ip route add "$PREFIXA" via "fd00:200::${GROUPNUMBER}"
    ### Provided the internal routing of your network is correct and has converged:
    ## You should now be able to ping your virtual network hosts
    ## connect to the ssh servers, use their FQDN if the DNS are configured
    ## properly, ...
}

