# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  # We need 2 extra interfaces besides the one from
  config.vm.network "private_network", ip: "10.0.0.1", auto_config: false
  config.vm.network "private_network", ip: "10.0.0.2", auto_config: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.synced_folder "./", "/home/vagrant/LINGI2142-setup"
  config.ssh.insert_key = "true"
  config.ssh.forward_x11 = "true"

  config.vm.provision "shell", path: "provision.sh"
end
