#!/bin/bash

# Towards STEV
ip link set dev CARN-eth0 up
#ip address add dev CARN-eth0 fd00:2:de::e/64

# Towards MICH
ip link set dev CARN-eth1 up
#ip address add dev CARN-eth1 fd00:2:ef::e/64

# Towards PYTH
ip link set dev CARN-eth2 up
#ip address add dev CARN-eth2 fd00:2:ce::e/64

# LAN
routing/setup_lan.py CARN-lan0

# QoS
./qos/qos.sh STEV CARN-eth0 MICH CARN-eth1 PYTH CARN-eth2

bird6 -s /tmp/CARN.ctl

# dhcp relay
dhcrelay -q -6 -l CARN-lan0.1 -l CARN-lan0.3 -u fd00:200:2:204::1%CARN-lan0 -u fd00:200:2:103::1%CARN-eth0 -u fd00:200:2:103::1%CARN-eth2 --no-pid

#Firewall
firewall/CARN.sh
ulogd -d

/usr/sbin/sshd

#radvd
radvd -n -C /etc/radvd.conf
