#!/bin/bash

ip link set dev LB1-eth0 up

routing/setup_lan.py LB1-eth0
/usr/sbin/sshd
#lighttpd -f /etc/lighttpd/lighttpd.conf
/usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf
ulogd -d
#firewall/CA1.sh
