#!/bin/bash

# Towards SH1C
ip link set dev MICH-eth0 up
#ip address add dev MICH-eth0 fd00:2:af::f/64

# Towards CARN
ip link set dev MICH-eth1 up
#ip address add dev MICH-eth1 fd00:2:ef::f/64

# LAN
routing/setup_lan.py MICH-lan0

# QoS
./qos/qos.sh SH1C MICH-eth0 CARN MICH-eth1

bird6 -s /tmp/MICH.ctl
/usr/sbin/sshd

# DHCP relay
dhcrelay -q -6 -l MICH-lan0.1 -l MICH-lan0.2 -l MICH-lan0.3 -l MICH-lan0.4 -u fd00:200:2:103::1%MICH-eth0 -u fd00:200:2:103::1%MICH-eth1 -u fd00:200:2:204::1%MICH-eth0 -u fd00:200:2:204::1%MICH-eth1 --no-pid

#Firewall
firewall/MICH.sh
ulogd -d

#radvd
radvd -n -C /etc/radvd.conf
