#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip -6 addr add fde4:10:12::2222/128 dev lo
ip -6 addr add fde4:10:23::2222/128 dev lo

# Assigning IP addr for P1-eth0
ip link set dev P2-eth0 up

# Assigning IP addr for P1-eth1
ip link set dev P2-eth1 up

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p2.api -i /tmp/p2_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p2_ospf.conf -z /tmp/p2.api -i /tmp/p2_ospf6d.pid -A 127.0.0.1


