#! /bin/sh
ldconfig
# Assigning IP addr for P1-eth0
ip link set dev P3-eth0 up
ip -6 addr add fde4:10:13::33/64 dev P3-eth0

# Assigning IP addr for P1-eth1
ip link set dev P3-eth1 up
ip -6 addr add fde4:10:23::33/64 dev P3-eth1

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p3.api -i /tmp/p3_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p3_ospf.conf -z /tmp/p3.api -i /tmp/p3_ospf6d.pid -A 127.0.0.1